name: Clojure CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "17"

      - name: Install Leiningen
        run: |
          mkdir -p ~/.lein
          curl -o /usr/local/bin/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x /usr/local/bin/lein
          lein --version

      - name: Test
        run: lein test

      # - name: Deploy artifacts (adjust this based on your project setup)
      #   run: lein uberjar

      # - name: Upload Uberjar as artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: my-app-uberjar
      #     path: target/my-app-0.1.0-standalone.jar
